### ISSUE TITLE
Web Server integration

### ISSUE THREAD

**Issue by CaptainYarb** [sholladay/handle-quit#1]
It might be worthwhile to invest in graceful closing for web servers, given the extensive use for API servers. We've accomplished this in our mini framework here by telling the server to close, which will prevent new connections from being established, and then tracking all requests until they finish as to not interrupt requests.

Example: https://github.com/nodecraft/appframe-express.js/blob/master/appframe-express.js#L124

**Comment by sholladay** [comment]
Are you asking for the ability to pass in a server instance and have it closed automatically?

In other words, currently you would do this:

```js
handleQuit(() => {
    server.close();
});
```

And you wish that were a bit shorter:

```js
handleQuit(server);
```

Am I understanding correctly? If not, please show how `handleQuit` would be used.

**Comment by sholladay** [comment]
Ping @blazedd, any thoughts on this?

This module is much better documented since you opened this issue. Maybe it already does what you want. If not, and this is a feature request, my best guess for what you were asking for is in my previous comment. Sounds like you just want a shortcut, but I'm not certain.

**Comment by sholladay** [comment]
Closing due to lack of response. I am happy to consider adding direct support for server instances, if anyone feels it would be helpful and makes a proposal.
